export declare enum EFrameCommand {
    RENDER_FRAME = "RENDER_FRAME",
    UPDATE_CANVAS_ORIGIN = "UPDATE_CANVAS_ORIGIN",
    UPDATE_CANVAS_RECT = "UPDATE_CANVAS_RECT",
    SWITCH_DRAW_TOOL = "SWITCH_DRAW_TOOL",
    REFRESH_RTREE = "REFRESH_RTREE",
    CLEAR_ALL_SELECTS = "CLEAR_ALL_SELECTS"
}
export declare enum EDrawToolCommand {
    BLANK_DROP = "BLANK_DROP",
    LINE = "LINE",
    CIRCLE = "CIRCLE"
}
export declare enum EOutEventCommand {
    INPUTS_CHANGED = "INPUTS_CHANGED",
    CANVASPROFILE_CHANGED = "CANVASPROFILE_CHANGED",
    RESOURCE_CHANGED = "RESOURCE_CHANGED",
    PROFILE_CHANGED = "PROFILE_CHANGED",
    DRAWLAYER_CHANGED = "DRAWLAYER_CHANGED",
    OPERATION_CHANGED = "OPERATION_CHANGED"
}
