export declare const OUT_EVENT_NS: string;
export declare enum EOutEventCommand {
    INPUTS_CHANGED = "INPUTS_CHANGED",
    CANVASPROFILE_CHANGED = "CANVASPROFILE_CHANGED",
    RESOURCE_CHANGED = "RESOURCE_CHANGED",
    PROFILE_CHANGED = "PROFILE_CHANGED"
}
