export declare enum EOperationAction {
    HISTORY_UNDO = "HISTORY_UNDO",
    HISTORY_REDO = "HISTORY_REDO",
    CREATE_ELEMENT = "CREATE_ELEMENT",
    MODIFY_ELEMENT = "MODIFY_ELEMENT",
    DELETE_ELEMENT = "DELETE_ELEMENT",
    REFRESH_DRAWLAYER = "REFRESH_DRAWLAYER",
    CREATED_DRAWLAYER = "CREATED_DRAWLAYER",
    DELETED_DRAWLAYER = "DELETED_DRAWLAYER",
    SWITCH_ACTIVE_DRAWLAYER = "SWITCH_ACTIVE_DRAWLAYER",
    CLEAR_ALL_ACTIVE_DRAWLAYER = "CLEAR_ALL_ACTIVE_DRAWLAYER",
    CLEAR_ALL_DRAWLAYER_ELEMENTS = "CLEAR_ALL_DRAWLAYER_ELEMENTS",
    IMPORT_DATASTR_START = "IMPORT_DATASTR_START",
    IMPORT_DATASTR_COMPLETE = "IMPORT_DATASTR_COMPLETE",
    EXPORT_DATASTR_START = "IMPORT_DATASTR_START",
    EXPORT_DATASTR_COMPLETE = "IMPORT_DATASTR_COMPLETE"
}
