export declare enum EFrameCommand {
    RENDER_FRAME = "RENDER_FRAME",
    UPDATE_CANVAS_ORIGIN = "UPDATE_CANVAS_ORIGIN",
    UPDATE_CANVAS_RECT = "UPDATE_CANVAS_RECT",
    SWITCH_DRAW_TOOL = "SWITCH_DRAW_TOOL",
    REFRESH_RTREE = "REFRESH_RTREE"
}
