import { DrawLayerController } from './controller/DrawLayerController';
import { ElementController } from './controller/ElementController';
import { InputInfo } from './tool/InputInfo';
import { px2mm as _px2mm } from './utils/Utils';
import { TDOMGetBoundingClientRectResult, TColorJSON, TDrawLayerItemResult, TElementItemResult, TResouceChangedData, TSystemConfigProfile, TCanvasProfileChangedData } from './types/Common';
import { SystemConfig } from './controller/SystemConfig';
import { CanvasController } from './controller/CanvasController';
import { MessageBus } from './utils/messageBus/MessageBus';
import { WindowMessageBridge } from './utils/messageBus/WindowMessageBridge';
export type InputInfoData = InputInfo;
export type DOMGetBoundingClientRectResult = TDOMGetBoundingClientRectResult;
export type ColorJSON = TColorJSON;
export type DrawLayerItemResult = TDrawLayerItemResult;
export type ElementItemResult = TElementItemResult;
export type ResouceChangedData = TResouceChangedData;
export type CanvasProfileChangedData = TCanvasProfileChangedData;
export type SystemConfigProfile = TSystemConfigProfile;
export * from './utils/Color';
export * from './geometry/Decimals';
export * from './geometry/DoubleKit';
export * from './geometry/Angles';
export * from './geometry/Vector2';
export * from './geometry/Vector3';
export * from './geometry/Matrix';
export * from './geometry/Matrix3';
export * from './geometry/Matrix4';
export declare const px2mm: typeof _px2mm;
export declare const messageBus: MessageBus;
export declare const windowMessageBridge: WindowMessageBridge;
export declare const DRAW_TOOL_COMMAND: any;
export declare class WebCanvas {
    private _canvasElement;
    private _drawToolManager;
    constructor(canvasElement: HTMLCanvasElement);
    init(): Promise<boolean>;
    get drawLayerController(): DrawLayerController;
    get elementController(): ElementController;
    get canvasController(): CanvasController;
    getCanvasRect(): TDOMGetBoundingClientRectResult;
    getDPI(): [number, number];
    getSystemConfig(): TSystemConfigProfile;
    getCanvasProfileData(): TCanvasProfileChangedData;
    applySystemConfig(key: keyof SystemConfig, value: any): void;
    setDrawToolCommand(type: string): void;
    forceRender(): void;
    resetCanvasView(): void;
    addInputsChangedListener(callback: (data: InputInfo) => void): void;
    addResourceChangedListener(callback: (data: TResouceChangedData) => void): void;
    addCanvasProfileChangedListener(callback: (data: TCanvasProfileChangedData) => void): void;
    addProfileListener(callback: (data: TSystemConfigProfile) => void): void;
}
export declare function createCanvasElement(containerElement: HTMLElement): HTMLCanvasElement;
